modLoader="javafml"
loaderVersion="[33,)"
license="MIT"

[[mods]]
modId="snowrealmagic"
version="${file.jarVersion}"
displayName="Snow! Real Magic!"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snowrealmagic"
description='''Tweak vanilla snow layer.'''

[[dependencies.snowrealmagic]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.3, 3.9)"
    ordering="BEFORE"
    side="BOTH"
